version: '3.8'

networks:
    inception:
        driver: bridge

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    volumes:
      - "/home/myagiz/data/mariadb:/var/lib/mysql"
    env_file:
      - .env
    expose:
      - 3306
    networks:
      - inception
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    restart: always
    volumes:
      - "/home/myagiz/data/wordpress:/var/www/html/wordpress"
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    restart: always
    volumes:
      - "/home/myagiz/data/wordpress:/var/www/html/wordpress"
    env_file:
      - .env
    expose:
      - 9000
    networks:
      - inception
